apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: nginx
    tier: backend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: nginx
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
      cloudcontrol.enabled: "true"
      cloudcontrol.index: "0"
      LAUNCHPAD_ENABLE: "true"
      LAUNCHPAD_COLOR: LIGHT_GREEN
      LAUNCHPAD_ROW: "0"
spec:
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
